name: Multi-Job Artifact Pipeline

on:
  push:
    branches: [ "main" ]
  # 👇 ADD THIS LINE to enable the manual "Run workflow" button in the UI
  workflow_dispatch: 

# 👇 CONCURRENCY ENGINE
concurrency:
  # Groups builds by the branch name (e.g., main)
  group: ${{ github.workflow }}-${{ github.ref }}
  # Set to 'true' if you want to cancel the older running build instantly when a new one comes in.
  # Set to 'false' if you want the older build to finish peacefully before the new one begins.
  cancel-in-progress: false 
  
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create a build file
        run: echo "Compiled assets from build number ${{ github.run_number }}" > build.txt
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-compiled-assets
          path: build.txt
      - name: Wait for cooling period
        run: sleep 1m
        shell: bash
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-compiled-assets
      - name: Read the asset file
        run: cat build.txt
      - name: Force failure
        run: exit 1
